const SearchActionsTypes = {
  START_CURRENT_SEARCH: 'START_CURRENT_SEARCH',
  FETCH_CURRENT_SEARCH: 'FETCH_CURRENT_SEARCH',
  ERROR_CURRENT_SEARCH: 'ERROR_CURRENT_SEARCH',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  SET_CURRENT_VALUE: 'SET_CURRENT_VALUE'
}

export default SearchActionsTypes;