const SearchActionsTypes = {
  START_CURRENT_SEARCH: 'START_CURRENT_SEARCH',
  FETCH_CURRENT_SEARCH: 'FETCH_CURRENT_SEARCH',
  ERROR_CURRENT_SEARCH: 'ERROR_CURRENT_SEARCH'
}

export default SearchActionsTypes;